routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('permisos', 'PermisoController');
Route::resource('salidas', 'SalidaController');
Route::get('capacitacion/{capacitacion}', 'PermisoController@showCap');
Route::get('viatico/{viatico}', 'PermisoController@showViatico');
Route::resource('viaticos', 'ViaticoController');

Route::get('/', function () {
    return view('Auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

app/Salida.php
<?php

namespace App;

use function foo\func;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Salida extends Model
{
    protected $fillable = ['user_id', 'descripcion', 'dia_salida', 'hora_salida', 'hora_llegada', 'horas_ocupado', 'horas_saldo', 'horas_inicial'];

    public function user(){
        return $this->belongsTo(User::class);
    }

    function totalHorasMes($id){
        return Salida::whereMonth('dia_salida', '=', date('m'))
            ->whereUserId($id)
            ->sum('horas_ocupado');
    }
}

app/Http/Controllers/SalidaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreSalida;
use App\Salida;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use \Carbon;
use Illuminate\Support\Facades\App;
use App\Events\SalidaFueCreada;

class SalidaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::findOrFail(Auth::id());
        $salidas = $user->salidas()->latest('dia_salida')->whereMonth('dia_salida', '=', date('m'))->paginate(5);
            return view('salida.index', compact('salidas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $salida = new Salida();

        return view('salida.create', compact('salida'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSalida $request)
    {
        $user = User::find(Auth::id());
        $dif = Carbon\Carbon::parse($request->hora_llegada)->diffInMinutes(Carbon\Carbon::parse($request->hora_salida));
        $ocupadoMes = $user->salidas()->latest()->whereMonth('dia_salida', '=', date('m'))->sum('horas_ocupado');

        if (($ocupadoMes + $dif) <= 120 ) {
            if ($salida = Salida::updateOrCreate($request->except('_token'))) {

                $diferencia = Carbon\Carbon::parse($request->hora_llegada)->diffInMinutes(Carbon\Carbon::parse($request->hora_salida));
                $salida->horas_ocupado = $diferencia;
                /*$salida->estado = 'impreso';*/
                $salida->save();

                event(new SalidaFueCreada($salida));

                return redirect()->route('salidas.index', $salida->id)->with('info', 'Nueva Salida creada!');
                }else
                    return redirect()->route('salidas.index')->with('info', 'Algo paso...!');
            } else
                return redirect()->route('salidas.index')->with('danger', 'Sobrepasa Limite de 2 horas!');
        }


    /**
     * Display the specified resource.
     *
     * @param  \App\Salida  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $salida = Salida::findOrFail($id);

        $view = view('salida.show', compact('salida'));
        $pdf = App::make('dompdf.wrapper');
        $pdf->loadHTML($view)->setPaper('a4', 'landscape')->setWarnings(false);

        return $pdf->stream('salida_'.$salida->id.'.pdf');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Salida  $salida
     * @return \Illuminate\Http\Response
     */
    public function edit(Salida $salida)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Salida  $salida
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Salida $salida)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Salida  $salida
     * @return \Illuminate\Http\Response
     */
    public function destroy(Salida $salida)
    {
        //
    }

}

resources/views/salida/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card card-default">
                    <div class="card-header">Nueva Salida</div>
                    @if(session()->has('info'))
                        <div class="alert alert-success">{{ session('info') }}</div>
                    @endif
                    <div class="card-body">
                        @include('salida.form', [ 'url' => 'salidas', 'method' => 'POST', 'action' => route('salidas.store')])
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/salida/form.blade.php
{{ Form::open([ 'url' => $url, 'method' => $method, 'action' => $action,]) }}

@csrf

{!! Form::hidden('user_id', Auth::user()->id) !!}

<div class="form-group">
    {!! Form::label('dia_salida', 'Fecha del Permiso') !!} {!! Form::date('dia_salida', $salida->dia_salida, ['class' => 'form-control'.($errors->has('dia_salida') ? ' is-invalid' : '')]) !!}
    @if ($errors->has('dia_salida'))
        <span class="invalid-feedback">
        <strong>{{ $errors->first('dia_salida') }}</strong>
    </span>
    @endif
</div>
<div class="row">
<div class="col form-group">
    {!! Form::label('hora_salida', 'Hora Salida') !!} {!! Form::time('hora_salida', $salida->hora_salida, ['class' => 'form-control'.($errors->has('hora_salida') ? ' is-invalid' : '')]) !!}
    @if ($errors->has('hora_salida'))
    <span class="invalid-feedback">
        <strong>{{ $errors->first('hora_salida') }}</strong>
    </span>
    @endif
</div>

<div class="col form-group">
    {!! Form::label('hora_llegada', 'Hora llegada') !!} {!! Form::time('hora_llegada', $salida->hora_llegada, ['class' => 'form-control'.($errors->has('hora_llegada') ? ' is-invalid' : '')]) !!}
    @if ($errors->has('hora_llegada'))
    <span class="invalid-feedback">
        <strong>{{ $errors->first('hora_llegada') }}</strong>
    </span>
    @endif
</div>
</div>
<div class="form-group">
    {!! Form::label('descripcion', 'Motivo') !!} {!! Form::textarea('descripcion', $salida->descripcion, ['class' => 'form-control'.($errors->has('descripcion') ? ' is-invalid' : ''),'rows' => "2"]) !!}
    @if ($errors->has('descripcion'))
    <span class="invalid-feedback">
        <strong>{{ $errors->first('descripcion') }}</strong>
    </span>
    @endif
</div>

<div class="row">
    <div class="col">
        {!! Form::submit('Guardar', ['class' => 'btn btn-primary btn-lg btn-block']) !!}
    </div>
    <div class="col">
        <a href="{{ url('salidas') }}">
            {{ Form::button('Cancelar', ['class' => 'btn btn-secondary btn-lg btn-block'] ) }}
        </a>
    </div>
</div>
{{ Form::close() }}

resources/views/salida/index.blade.php
<?php $salida = new App\Salida; ?>

@extends('layouts.app')
@section('content')

<div class="container">
    <div class=" row py-5">
        <div class="col-4">
            <h2 class="title">Permiso Salida Especial</h2>
        </div>
        <div class="col-4">
            <span class="badge badge-pill badge-primary"> Total ocupado: {{ $salida->totalHorasMes(Auth::id()) }}</span>
        </div>
    </div>

    @if(session('info'))
        <div id="alert" class="alert alert-success alert-dismissible fade show" role="alert">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>{{ session('info') }}</strong>
        </div>
        @elseif(session('danger'))
            <div class="alert alert-danger text-center">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ session('danger') }}</strong>
            </div>
    @endif
            <div class="row">

                {{--{{ $mes_actual }}--}}

                <div class="col">
                    <table class="table table-striped table">
                        <thead>
                            <tr>
                                <th>Fecha Solicitud</th>
                                <th>Hora Salida</th>
                                <th>Hora Llegada</th>
                                <th>Minutos Ocupado</th>
                                <th>Motivo</th>
                                {{--<th>Minutos restantes (de 120 al mes)</th>--}}
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($salidas as $salida)

                            <tr>
                                <td>{{ Carbon\Carbon::parse($salida->dia_salida)->format("d-m-Y") }}</td>

                                <td>{{ $hora_salida = Carbon\Carbon::parse($salida->hora_salida)->format("H:i") }}</td>
                                <td>{{ $hora_llegada = Carbon\Carbon::parse($salida->hora_llegada)->format("H:i") }}</td>

                                <td>{{ $salida->horas_ocupado }}</td>

                                <td>{{ strtoupper($salida->descripcion) }}</td>
                                {{--<td>{{ $salida->horas_saldo }}</td>--}}
                                <td><a class="btn btn-outline-primary" href="{{ url('salidas/'.$salida->id) }}" target="_blank">Print <i class="fas fa-print"></i></a></td>
                                
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="form-group">
                        <a id="new" class="btn btn-success" href="{{ route('salidas.create') }}">
                            Nuevo <i class="fas fa-plus"></i>
                        </a>
                        <a href="{{ route('home') }}" class="btn btn-secondary">Atras</a>

                    </div>
                    <div>
                        {{ $salidas->links() }}
                    </div>
                </div>
            </div>
</div>
<script>
    $(document).ready(function(){
        $('#alert').delay(2000).slideUp(200, function(){
            $(this).remove();
        });
    }, 5000);
</script>
@stop

resources/views/salida/show.blade.php
<?php $s = new App\Salida; ?>

@extends('layouts.app')
@section('nav')
    @stop
@section('content')

    <div class="container">
        <div class="col-sm-3 clearfix text-center">
            <img style="height: 100px; width: 100px" src="{{ asset('img/logo.png') }}" alt="logo">
            <h6 class="font-weight-bold">Hospital De Licanten</h6>
            <h6 class="font-weight-bold">Oficina de Recursos Humanos</h6>
        </div>
        <div class="row">
            <div class="col-sm-8 float-right py-3">
                <h5><u>PERMISO DE SALIDA ESPECIAL Nº {{ $salida->id }}</u></h5>
            </div>
        </div>
        <div class="row">
            <div class="col pt-5">
                <table class="table-striped py-5">
                    <thead>
                        <tr><th>FECHA SOLICITUD: </th> <td><u>{{ Carbon\Carbon::parse($salida->created_at)->format("d-m-Y") }}</u></td><th>SERVICIO: </th> <td><u>{{ strtoupper($salida->user->unidad->nombre) }}</u></td></tr>
                        <tr><th>NOMBRES Y APELLIDOS: </th><td><u>{{  strtoupper($salida->user->name) }} {{ strtoupper($salida->user->apellido_paterno) }} {{ strtoupper($salida->user->apellido_materno) }}</u></td></tr>
                        <tr><th>FECHA DE PERMISO: </th><td><u>{{ Carbon\Carbon::parse($salida->dia_salida)->format("d-m-Y") }}</u></td></tr>
                        <tr><th>MOTIVO DE SALIDA: </th><td><u>{{ strtoupper($salida->descripcion) }}</u></td></tr>
                        <tr><th>HORA DE SALIDA: </th><td><u>{{ Carbon\Carbon::parse($salida->hora_salida)->format("H:i") }}</u></td><th>HORA LLEGADA: </th><td><u>{{ Carbon\Carbon::parse($salida->hora_llegada)->format("H:i") }}</u></td></tr>
                    </thead>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <span class="badge badge-pill badge-success rounded">Minutos Ocupados: {{ $s->totalHorasMes(Auth::id()) }} de 120</span>
            </div>
        </div>

        <div class="row">
            <div class="col clearfix fixed-bottom">
                <span class="float-left font-weight-bold">Firma Funcionario(a) Solicitante</span>

                <span class="float-right font-weight-bold">VºBº Jefe Directo</span>
            </div>
        </div>
    </div>

    <style>
        body{
            background: #ffffff;
        }
    </style>

    @stop